#include "commandHandler/commandHandler.h"
#include "terminator/terminator.h"
#include "processGreeter/processGreeter.h"
#include "getTypeAsString/getTypeAsString.h"
#include "print/print.h"
#include "getCPlusPlusVersionAsString/getCPlusPlusVersionAsString.h"